### PR TITLE
Fixes #52 Opening of social link in new tab 1.Added target attribute to Link component so that any link when clicked would open in new tab

### LINKED ISSUE #52: Social Icons should open in next tab
### Describe the bug

There are SocialLink/Icon based component which redirects the page to proper social page like instagram. Ideally these icons when clicked should be opened in a separate tab.

### Steps To Reproduce

1. In terminal start storybook `yarn storybook`
2. Go to socialLink / socialIcon
3. Click on Facebook / Instagram

Notice that it opens in current tab only

### Expected Behavior

The social page should open in a separate tab.

### Screenshots/Videos

_No response_

### What device are you using?

_No response_

### What is your operating system version?

_No response_

### What browser are you using?

_No response_

### What is your browser version?

_No response_

### What is your screen resolution?

_No response_

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by vanamraghu**
## What type of PR is this? (check all applicable)

- [ ] Bug Fix

## Description

Fixed issue in opening the social link in new tab

## Related Tickets & Documents

- Related Issue #52
- Closes #52

## QA Instructions, Screenshots, Recordings

Open storybook for the social link and provide the href (valid one ) and click on the icon that should display the provided href in new tab

### CODE REVIEW

File: src/components/SocialLink.jsx [hunk 1]
```diff
@@ -5,7 +5,7 @@ import PropTypes from "prop-types";
 const SocialLink = ({ icon, href, text }) => {
   return (
     <div>
-      <Link to={href}>
+      <Link to={href} target={"_blank"}>
```
Comment (rt4914) [inline src/components/SocialLink.jsx:8]: We use `{}` when we want to use jsx mainly when using variables.
In this case it can be simply `target="_blank"`

**Review by rt4914 — CHANGES_REQUESTED** [review]
@vanamraghu Minor change.

File: src/components/SocialLink.jsx (hunk 1 above)
Comment (vanamraghu) [reply src/components/SocialLink.jsx:8]: Fixed

**Review by rt4914 — APPROVED** [review]
